# 端口号
server:
  port: 8002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bc_xueyuan
    username: root
    password: Fyk@20010628
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev # 环境设置
  application:
    name: service-cos # 服务名
# 腾讯云 COS
qcloud:
  cos:
    file:
      secretId:  # id
      secretKey:   # key
      COS_REGION:  # 地域
      bucket:  # 存储桶